// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ7YU-ZcMoQ6kZU4RhBsLImHH625HCb1k',
    appId: '1:96526796420:web:cd41d6eb54901d925a24d1',
    messagingSenderId: '96526796420',
    projectId: 'garbages-detection',
    authDomain: 'garbages-detection.firebaseapp.com',
    storageBucket: 'garbages-detection.firebasestorage.app',
    measurementId: 'G-3LS9WLNC3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLfFjv1T_hThcxQFTpvSoa0JTy8WSk8KA',
    appId: '1:96526796420:android:d0b9ed09e37edf335a24d1',
    messagingSenderId: '96526796420',
    projectId: 'garbages-detection',
    storageBucket: 'garbages-detection.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLqA9tzvpKoEMN9zGgoHgnNQmWN1LF46A',
    appId: '1:96526796420:ios:d0a600878a67e41c5a24d1',
    messagingSenderId: '96526796420',
    projectId: 'garbages-detection',
    storageBucket: 'garbages-detection.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLqA9tzvpKoEMN9zGgoHgnNQmWN1LF46A',
    appId: '1:96526796420:ios:d0a600878a67e41c5a24d1',
    messagingSenderId: '96526796420',
    projectId: 'garbages-detection',
    storageBucket: 'garbages-detection.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ7YU-ZcMoQ6kZU4RhBsLImHH625HCb1k',
    appId: '1:96526796420:web:502d8a78bde6f1c45a24d1',
    messagingSenderId: '96526796420',
    projectId: 'garbages-detection',
    authDomain: 'garbages-detection.firebaseapp.com',
    storageBucket: 'garbages-detection.firebasestorage.app',
    measurementId: 'G-2ZEXZV5W4Q',
  );
}
